Задание 1

In [2]:
import numpy as np
a = np.loadtxt("minutes_n_ingredients.csv",
                    delimiter=",",skiprows = 1, dtype=int)


In [ ]:
b=a[:5]
b

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

задание 2

In [4]:
ingsr=0
c=np.mean(a, axis = 0)#среднее значение
print(c[1].astype(int))
ingsr=c[2].astype(int)
print(ingsr)

print(np.min(a[1]))# min
print(np.min(a[2]))

print(np.max(a[1]))# max
print(np.max(a[2]))

med=np.median(a, axis=0)#медиана
print(med[1:3].astype(int))

21601
9
7
6
23891
94746
[40  9]


Задание 3

In [5]:
d=np.quantile(a,.75,axis = 0)
e=d[1].astype(int)
f=np.clip(a[:,1],None,e)
f

array([60, 25, 10, ..., 65,  5, 65])

Задание 4

In [6]:
zero=(a[:,1] == 0).sum()
a[:,1]= np.clip(a[:,1], 1, None)
print(zero)

479


Задание 5

In [ ]:
u=np.stack((a[:,1],a[:,2]), axis=1)
u1= np.unique(u, axis=0)
print(u1.shape[0])

4183


Задание 6

In [ ]:
u2, counts = np.unique(a[:,2], return_counts=True)
dict(zip(u2, counts))

{1: 13,
 2: 926,
 3: 2895,
 4: 5515,
 5: 7913,
 6: 9376,
 7: 10628,
 8: 10951,
 9: 10585,
 10: 9591,
 11: 8297,
 12: 6605,
 13: 4997,
 14: 3663,
 15: 2595,
 16: 1767,
 17: 1246,
 18: 790,
 19: 573,
 20: 376,
 21: 217,
 22: 161,
 23: 105,
 24: 69,
 25: 50,
 26: 28,
 27: 16,
 28: 16,
 29: 12,
 30: 12,
 31: 3,
 32: 1,
 33: 2,
 34: 1,
 35: 3,
 37: 1,
 39: 1}

задание 7


In [ ]:
five= np.where( a[:,2]<= 5)
new = a[five]
new

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

задание 8

In [ ]:
h=a[:,1]/a[:,2]
print(h.astype(int))
print(h.max())

[ 3  3  1 ...  4  1 10]
268435455.875


Задание 9

In [ ]:
sorts =np.sort(a[:,1])[::-1]
sorts=sorts[:100]
print(sorts.sum()/100)

21518445.39


Задание 10

In [8]:
print(a[np.random.randint(0, a.shape[0], size = 10)])

[[122817     40      5]
 [437232      9      4]
 [306135     35     10]
 [167556     35      7]
 [ 13168    130      5]
 [461292     35     13]
 [323737     35      7]
 [ 39100     41     10]
 [278836     90     13]
 [ 78971     30     11]]


Задание 11

In [ ]:
Q=np.where(a[:,2]<ingsr)
pers=(len(a[Q])/len(a[:,2]))*100
print(pers)

48.217
